### ISSUE TITLE
Bubble when generating in water

### ISSUE THREAD

**Issue by Aceplante2** [HexagonNico/SpiderCaves#6]
The center cave creates a water bubble when generating in water forge 1.20.1

![bubble](https://github.com/HexagonNico/SpiderCaves/assets/101857505/8452ef2d-b223-447d-a6ee-054bc16679c6)

**Comment by HexagonNico** [comment]
Are you sure that isn't a Spider Dungeon from Yung' Better Dungeons?

**Comment by Aceplante2** [comment]
I am not, I can try to check if I still have that world

**Comment by HexagonNico** [comment]
No, no achievements here.
